import art_portrait_idol_img_1 from '../assets/homedecor/idolimg.jpg'
import home_decor_crystal_img_1 from '../assets/homedecor/crystal_img.jpg'
import home_decor_crystal_img_2 from '../assets/homedecor/carpets_img_2.jpg'
import home_decor_dining_img_1 from '../assets/homedecor/dining.jpg'
import furniture_table_img_1 from '../assets/homedecor/table.jpg'
import furniture_carpets_img_1 from '../assets/homedecor/carpets.jpg'
import jwellary_box_img_1 from '../assets/homedecor/jwebox.jpg'
import home_decor_jug_img_1 from '../assets/homedecor/jug.jpg'
import home_decor_dinset_img_1 from '../assets/homedecor/dineset.jpg'
import light_lamp_lamp_img_1 from '../assets/homedecor/lamps.jpg'
import light_lamp_lamp_img_2 from '../assets/homedecor/lamp_img_2.jpg'

const products = [
    {
        id: 1,
        title: "Metal Lantern Lamp Set of 3",
        brand: "Kottanz",
        image_1: light_lamp_lamp_img_1,
        image_2: light_lamp_lamp_img_2,
        image_3: "",
        price: 1459.00,
        discount: 1299.00,
        quantity: 20,
        created_at: "2024-02-02T12:12",
        category: "lights and chandelier",
        color: "golden",
        size: "22 inch",
        material: "carbon plastic",
        description: "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
        rating: 4,
    },
    {
        id: 2,
        title: "TRIPPING",
        brand: "TRIPPING Gold Antique Squre gate Pole Pilar lamp",
        image_1: home_decor_crystal_img_1,
        image_2: home_decor_crystal_img_2,
        image_3: "",
        price: 2999.00,
        discount: 2439.00,
        quantity: 15,
        created_at: "2024-01-02T12:45",
        category: "lights and chandelier",
        color: "golden",
        size: "12inch",
        material: "plastic",
        description: "This is a beautiful gate lamp. It is made of metal and has a beautiful design. It would look great in any garden.This is a new design outdoor lamp. It is made of high quality iron. It is waterproof and dustproof. It is very easy to install and use. It is a good choice for your outdoor lighting.",
        rating: 4,
    },
    {
        id: 8,
        brand: '	Shri & Sam',
        title: "Shri & Sam Stainless Steel Delight Solid Dinner Set",
        description: "Made of premium quality 200 series grade stainless stee",
        description2: "Included Components: 8-Pieces Dinner Plates, 8-Pieces Side Plates, 8-Pieces Glasses, 16-Pieces Bowls, 8-Pieces Chutney Bowls, 8-Pieces Pudding Bowls, 3-Pieces Serving Bowl, 3-Pieces Serving Bowl Lid, 1-Piece Perforated Serving Basting Spoon, 1-Piece Solid Serving Basting Spoon, 1-Piece Serving Rice Spoon, 1-Piece Serving Skimmer,1-Piece Salad Tong, 1-Piece Serving Ladle, 8-Pieces Fruit Fork, 8-Pieces Dessert Spoons, 8-Pieces Dessert Fork, 8-Pieces Ice Cream Spoon, 1-Piece Salad Bowl",
        price: 9999.00,
        discounted: 4199.00,
        product_code: "ASD4562124578", // 13 char
        currency: "₹",
        categoryName: "Home & Decor",
        image_1: home_decor_dinset_img_1,
        rating: 3,
        color: "Glossy silver",
        material: "steel",
        dimension: "Multiple",
        weight: "200g",
        quanity: 101,
    },
    {
        id: 9,
        brand: 'CROCKERY WALA AND COMPANY',
        title: "Handmade Brass Jug Pitcher",
        description: "Crockery Wala And Company Handmade Brass Jug Pitcher with 4 Legs for Serving Drinking Water, Home Decor Gift Item (1750 Ml)",
        description2: "Wet the Items with water, sour with Pitambari powder for extra shine, wash well under running water, wipe clean with a dry cloth, do not use steel wool or wire mesh for cleaning, always clean with a sponge and liquid soap.",
        price: 4000.00,
        discounted: 3201.00,
        product_code: "ASD4562123456", // 13 char
        currency: "₹",
        categoryName: "Jwellary & Pearls",
        image_1: home_decor_jug_img_1,
        rating: 2,
        color: "Golden",
        material: "Brass",
        dimension: "14W x 20H Centimeters",
        weight: "1.75litre",
        quanity: 45,
    },
    {
        id: 10,
        brand: 'CrazyInk',
        title: "Jewel Organizer Box Hand Carved Carvings",
        description: "CrazyInk Wooden Jewellery Box for Women and men couole ring | Jewel Organizer Box Hand Carved Carvings,Gift Items (228)",
        description2: "Also can be used to keep precious stones, watches, tarot cards, herbs, Feng shui items and add a touch of class to your dressing table or any other desk.",
        price: 799.00,
        discounted: 285.00,
        product_code: "ASD4562123456", // 13 char
        currency: "₹",
        categoryName: "Jwellary & Pearls",
        image_1: jwellary_box_img_1,
        rating: 3,
        color: "Multicolour",
        material: "Wood",
        dimension: "standard",
        weight: "30g",
        quanity: 45,
    },
    {
        id: 11,
        brand: '	BH COLLECTION',
        title: "Silk Touch Kashmiri Look Floral Carpet ",
        description: "NEW CRAETION JUST LAUNCHED HIGH QUALITY EMBOSS MODERN CARPET WITH COMPETITIVE PRICE",
        description2: "Anti slip, it fixes very well to your home floor surface , very comfortable carpet because its density and thickness is very high which completes your dream of carpet.",
        price: 6499.00,
        discounted: 3680.00,
        product_code: "ASD4562123456", // 13 char
        currency: "₹",
        categoryName: "Furniture & Carpets",
        image_1: furniture_carpets_img_1,
        rating: 4,
        color: "Golden",
        material: "Wool, Cotton",
        dimension: "3 X 5 Feet",
        weight: "320g",
        quanity: 45,
    },
    {
        id: 12,
        brand: 'UHUD CRAFTS',
        title: "Wooden Fold-able Side",
        description: "UHUD CRAFTS Beautiful Antique Wooden Fold-able Side Table/End Table/Plant Stand/Stool Living Room Kids Play Furniture Table Round Shape",
        description2: "This multipurpose table can be used for any showpiece on it , plant stand and more.Antique Foldable table, easy to carry anywhere. A perfect gift item for you.Deco Paint; Assembly Instructions: Diy; Special Features: Collapsible; Size Name: Medium",
        price: 1599.00,
        discounted: 429.00,
        product_code: "ASD4562123456", // 13 char
        currency: "₹",
        categoryName: "Furniture & Carpets",
        image_1: furniture_table_img_1,
        rating: 4,
        color: "White",
        material: "Wood",
        dimension: "30D x 30W x 33H Centimeters",
        weight: "320g",
        quanity: 45,
    },
    {
        id: 13,
        brand: 'Paartha Saarthi',
        title: "Rajasthani Brass Dining Table Chair Maharaja Set",
        description: "Paartha Saarthi Rajasthani Antique Decorative Handcrafted Vintage Handmade Elegant Designer Brass Dining Table Chair Maharaja Set Showpiece",
        description2: "These items have antique elegant design that gives addition to you Home decor or can be use for decorating your Restaurants, Bars, Cafe,etc.;The classically designed statue is just perfect to station at home & office and also to gift someone special. Handcrafted item is being made by combination of contemporary & traditional methods. Very appealing and eye catching traditional design to use as a home",
        price: 999.00,
        discounted: 523,
        product_code: "ASD4526589789", // 13 char
        currency: "₹",
        categoryName: "Home & Decor",
        image_1: home_decor_dining_img_1,
        rating: 3,
        color: "Golden",
        material: "Bras",
        dimension: "Standard",
        weight: "30g",
        quanity: 85,
    },
    {
        id: 14,
        brand: 'Seetara',
        title: "Seetara Amethyst Crystal Tree",
        description: "Crystal Tree Decoration Item for Home Decor, Office (300 Beads) - Showpiece Decorative Item for Good Luck Money & Healing - Vastu Item for House, Gifting",
        description2: "The purple crystal amethyst, also known as metamorphosis, stimulates the third eye chakra and aids in balancing and healing the physical, mental, and emotional bodies.",
        price: 2999.00,
        discounted: 1067,
        product_code: "ASD4562356987", // 13 char
        currency: "₹",
        categoryName: "Home & Decor",
        image_1: home_decor_crystal_img_1,
        rating: 3,
        color: "Purple",
        material: "Wood",
        dimension: "15D x 5W x 15H Centimeters",
        weight: "30g",
        quanity: 45,
    },
    {
        id: 15,
        brand: 'Bhimonee Decor',
        title: "Handmade Copper Balaji Idol",
        description: "Copper Idols India - By Bhimonee Decor , 2.25 inches, Handmade Copper Balaji Idol Spl, 30 Grams,",
        description2: "Special Features: Detailed hand work and have beautiful hand work of skilled Indian artist. With every purchase you are supporting a artisan’s family.",
        price: 404.00,
        product_code: "ASD4562356987", // 13 char
        currency: "₹",
        categoryName: "Statue & Portraits",
        image_1: art_portrait_idol_img_1,
        rating: 4,
        color: "copper, patina antique",
        material: "Copper",
        dimension: "25L x 15W x 60H Millimeters",
        weight: "30g",
        quanity: 45,
    },
]

export {products}